package detector

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	appconfig "github.com/LFroesch/logdog/internal/config"
)

type GoLanguage struct{}

func (g *GoLanguage) Name() string {
	return "Go"
}

func (g *GoLanguage) Detect(projectPath string) bool {
	goModPath := filepath.Join(projectPath, "go.mod")
	_, err := os.Stat(goModPath)
	return err == nil
}

func (g *GoLanguage) Install(projectPath string, cfg Config) error {
	projectLogDir := cfg.OutputDir
	if projectLogDir == "" {
		projectLogDir = appconfig.ProjectLogDir(projectPath)
	}

	if err := os.MkdirAll(projectLogDir, 0755); err != nil {
		return fmt.Errorf("failed to create logs directory: %w", err)
	}

	// Create internal/logdog directory
	internalDir := filepath.Join(projectPath, "internal", "logdog")
	if err := os.MkdirAll(internalDir, 0755); err != nil {
		return fmt.Errorf("failed to create internal directory: %w", err)
	}

	loggerPath := filepath.Join(internalDir, "logger.go")

	updatedConfig := cfg
	updatedConfig.OutputDir = projectLogDir

	if err := g.generateLogger(loggerPath, updatedConfig); err != nil {
		return fmt.Errorf("failed to generate logger: %w", err)
	}

	// Generate README.md
	readmePath := filepath.Join(internalDir, "README.md")
	if err := g.generateReadme(readmePath); err != nil {
		return fmt.Errorf("failed to generate README: %w", err)
	}

	return nil
}

func (g *GoLanguage) generateReadme(outputPath string) error {
	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	_, err = file.WriteString(readmeContent)
	return err
}

func (g *GoLanguage) InstalledPath(projectPath string) string {
	return filepath.Join(projectPath, "internal", "logdog", "logger.go")
}

func (g *GoLanguage) GetLogPaths(projectPath string) []string {
	logsDir := appconfig.ProjectLogDir(projectPath)
	var paths []string

	filepath.Walk(logsDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() && (filepath.Ext(path) == ".jsonl" || filepath.Ext(path) == ".json") {
			paths = append(paths, path)
		}
		return nil
	})

	return paths
}

func (g *GoLanguage) generateLogger(outputPath string, config Config) error {
	tmpl := template.Must(template.New("logger").Parse(goLoggerTemplate))

	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()

	data := struct {
		Config Config
	}{
		Config: config,
	}

	return tmpl.Execute(file, data)
}

const readmeContent = `# 🐕 Logdog

A TUI-based logging utility that makes structured logging simple and consistent across Go projects.

## What is Logdog?

Logdog is a terminal-based app that:
- **Detects** Go projects automatically
- **Generates** a logging package for your project
- **Creates** structured JSON logs with daily rotation
- **Provides** a user-friendly API for logging

## Quick Start

This logger was generated by Logdog. To use it in your code:

` + "```go" + `
import "your-project/internal/logdog"

func main() {
   // Simple message
   logdog.Info("Application started")
   
   // With additional data
   logdog.Info("User logged in", "user_id", 123, "username", "john")
   
   // Error with context
   logdog.Error("Database error", "table", "users", "operation", "insert")
}
` + "```" + `

## API Reference

### Basic Logging
` + "```go" + `
logdog.Debug("Debug message")
logdog.Info("Info message") 
logdog.Warn("Warning message")
logdog.Error("Error message")
` + "```" + `

### With Additional Data
` + "```go" + `
// Pass key-value pairs as arguments
logdog.Info("User action",
   "user_id", 123,
   "action", "login",
   "ip", "192.168.1.1")
` + "```" + `

### Named Loggers (split by concern)
` + "```go" + `
// Package-level named loggers write to their own file and are stamped with
// ` + "`\"logger\":\"<name>\"`" + ` on every entry.
var (
   authLog = logdog.New("auth")
   dbLog   = logdog.New("db")
)

authLog.Info("login failed", "user_id", 123)   // → auth-YYYY-MM-DD.jsonl
dbLog.Error("query timeout", "table", "users") // → db-YYYY-MM-DD.jsonl
logdog.Info("server started")                    // → default-YYYY-MM-DD.jsonl
` + "```" + `

Options: ` + "`logdog.WithDir(\"/some/path\")`" + ` sends a named logger to a different folder; ` + "`logdog.WithLevel(logdog.DEBUG)`" + ` sets its minimum level.

## Log Output

The default logger writes to ` + "`~/.local/share/logdog/<project-name>/logs/default-YYYY-MM-DD.jsonl`" + `. Named loggers sit alongside it (e.g. ` + "`auth-YYYY-MM-DD.jsonl`" + `). Every entry is JSON Lines:

` + "```json" + `
{
 "timestamp": "2024-01-15T14:30:45Z",
 "level": "INFO",
 "logger": "default",
 "message": "User logged in",
 "data": {
   "user_id": 123,
   "username": "john",
   "ip": "192.168.1.1"
 }
}
` + "```" + `

## File Structure

Your project now has:
` + "```" + `
your-project/
├── internal/logdog/
│   ├── logger.go          # Generated logging package
│   └── README.md          # This documentation
└── go.mod

~/.local/share/logdog/
└── your-project/
    └── logs/
        ├── default-2024-01-15.jsonl
        ├── auth-2024-01-15.jsonl
        └── db-2024-01-15.jsonl
` + "```" + `

## Best Practices

1. **Use descriptive messages**: ` + "`\"User authentication failed\"`" + ` not ` + "`\"Error\"`" + `
2. **Include relevant context**: Always add user IDs, request IDs, etc.
3. **Use appropriate log levels**: 
  - ` + "`Debug`" + `: Development/troubleshooting info
  - ` + "`Info`" + `: Normal application events
  - ` + "`Warn`" + `: Unusual but handled situations
  - ` + "`Error`" + `: Actual problems that need attention
4. **Be consistent**: Use the same field names across your app

## Examples

### Web Server Logging
` + "```go" + `
// Request logging
logdog.Info("HTTP request", 
   "method", r.Method,
   "path", r.URL.Path,
   "user_id", userID,
   "ip", r.RemoteAddr)

// Error handling
if err != nil {
   logdog.Error("Database query failed", 
       "user_id", userID,
       "error", err.Error(),
       "query", "SELECT * FROM users")
   return
}

// Business events
logdog.Info("Order created",
   "user_id", userID,
   "order_id", order.ID,
   "total", order.Total)
` + "```" + `

### Background Jobs
` + "```go" + `
logdog.Info("Job started", "job_type", "email_sender", "batch_size", 100)

for _, email := range emails {
   if err := sendEmail(email); err != nil {
       logdog.Error("Email send failed", 
           "recipient", email.To,
           "template", email.Template,
           "error", err.Error())
       continue
   }
   logdog.Debug("Email sent", "recipient", email.To)
}

logdog.Info("Job completed", "sent", sentCount, "failed", failedCount)
` + "```" + `

---

Generated by Logdog - Simple structured logging for Go projects.`

const goLoggerTemplate = `package logdog

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

type LogLevel string

const (
	DEBUG LogLevel = "DEBUG"
	INFO  LogLevel = "INFO"
	WARN  LogLevel = "WARN"
	ERROR LogLevel = "ERROR"
)

type LogEntry struct {
	Timestamp string                 ` + "`json:\"timestamp\"`" + `
	Level     LogLevel               ` + "`json:\"level\"`" + `
	Logger    string                 ` + "`json:\"logger\"`" + `
	Message   string                 ` + "`json:\"message\"`" + `
	Data      map[string]interface{} ` + "`json:\"data,omitempty\"`" + `
}

type Logger struct {
	mu          sync.Mutex
	name        string
	logLevel    LogLevel
	logDir      string
	file        *os.File
	currentDate string
}

// Option configures a Logger created with New.
type Option func(*Logger)

// WithDir overrides the directory a named logger writes to.
// By default a named logger writes alongside the default logger.
func WithDir(dir string) Option {
	return func(l *Logger) { l.logDir = dir }
}

// WithLevel sets the minimum level for a named logger.
func WithLevel(level LogLevel) Option {
	return func(l *Logger) { l.logLevel = level }
}

var defaultLogger *Logger
var once sync.Once

func baseDir() string {
	if dir := os.Getenv("LOGDOG_DIR"); dir != "" {
		return dir
	}
	return "{{.Config.OutputDir}}"
}

func init() {
	once.Do(func() {
		defaultLogger = &Logger{
			name:     "default",
			logLevel: INFO,
			logDir:   baseDir(),
		}
	})
}

// New returns a named logger that writes to ` + "`<name>-YYYY-MM-DD.jsonl`" + ` in the
// same directory as the default logger. Each entry is stamped with the name
// so downstream tooling can filter by logger.
//
//	var authLog = logdog.New("auth")
//	authLog.Info("login failed", "user_id", id)
func New(name string, opts ...Option) *Logger {
	l := &Logger{
		name:     name,
		logLevel: INFO,
		logDir:   baseDir(),
	}
	for _, opt := range opts {
		opt(l)
	}
	return l
}

// SetLevel sets the minimum log level for the default logger.
func SetLevel(level LogLevel) {
	defaultLogger.mu.Lock()
	defer defaultLogger.mu.Unlock()
	defaultLogger.logLevel = level
}

// SetLevel sets the minimum log level for this named logger.
func (l *Logger) SetLevel(level LogLevel) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.logLevel = level
}

// Close flushes and closes the default logger's open file. Call on shutdown.
func Close() {
	defaultLogger.Close()
}

// Close flushes and closes this named logger's open file.
func (l *Logger) Close() {
	l.mu.Lock()
	defer l.mu.Unlock()
	if l.file != nil {
		l.file.Close()
		l.file = nil
	}
}

func levelRank(l LogLevel) int {
	switch l {
	case DEBUG:
		return 0
	case INFO:
		return 1
	case WARN:
		return 2
	case ERROR:
		return 3
	}
	return 1
}

func (l *Logger) rotate(today string) error {
	if l.file != nil {
		l.file.Close()
		l.file = nil
	}
	if err := os.MkdirAll(l.logDir, 0755); err != nil {
		return err
	}
	logPath := filepath.Join(l.logDir, fmt.Sprintf("%s-%s.jsonl", l.name, today))
	f, err := os.OpenFile(logPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	l.file = f
	l.currentDate = today
	return nil
}

func (l *Logger) log(level LogLevel, message string, data map[string]interface{}) {
	l.mu.Lock()
	defer l.mu.Unlock()

	if levelRank(level) < levelRank(l.logLevel) {
		return
	}

	now := time.Now()
	today := now.Format("2006-01-02")
	if l.file == nil || l.currentDate != today {
		if err := l.rotate(today); err != nil {
			return
		}
	}

	entry := LogEntry{
		Timestamp: now.Format(time.RFC3339),
		Level:     level,
		Logger:    l.name,
		Message:   message,
		Data:      data,
	}
	jsonData, _ := json.Marshal(entry)
	fmt.Fprintln(l.file, string(jsonData))
}

// Logging methods on a named Logger.
func (l *Logger) Error(message string, args ...interface{}) { l.log(ERROR, message, buildData(args...)) }
func (l *Logger) Warn(message string, args ...interface{})  { l.log(WARN, message, buildData(args...)) }
func (l *Logger) Info(message string, args ...interface{})  { l.log(INFO, message, buildData(args...)) }
func (l *Logger) Debug(message string, args ...interface{}) { l.log(DEBUG, message, buildData(args...)) }

func buildData(args ...interface{}) map[string]interface{} {
	if len(args) == 0 {
		return nil
	}
	data := make(map[string]interface{}, len(args)/2)
	for i := 0; i+1 < len(args); i += 2 {
		if key, ok := args[i].(string); ok {
			data[key] = args[i+1]
		}
	}
	return data
}

// Package-level helpers write to the default logger (name = "default").
func Error(message string, args ...interface{}) { defaultLogger.log(ERROR, message, buildData(args...)) }
func Warn(message string, args ...interface{})  { defaultLogger.log(WARN, message, buildData(args...)) }
func Info(message string, args ...interface{})  { defaultLogger.log(INFO, message, buildData(args...)) }
func Debug(message string, args ...interface{}) { defaultLogger.log(DEBUG, message, buildData(args...)) }
`
